export enum BlockType {
  TRIGGER = 0,
  HTTP = 1,
  VARIABLE = 2,
  DICTIONARY = 3,
  FORK = 4,
  LOOP = 5,
  FILTER = 6,
  SCRIPT = 7,
  CONDITION = 8,
  DELAY = 9,
  KEY = 10,
  CONTROL_VALIDATION = 11,
  CONTROL_PERSISTENCE = 12,
  TAG = 13,
  CONNECTOR = 14
}